export const SOURCE_CHANNELS = Object.freeze({
  SFTP: 'SFTP',
  EMAIL: 'EMAIL',
  MAIL: 'MAIL',
  FAX: 'FAX',
  API: 'API',
  PARTNER_DASHBOARD: 'PARTNER_DASHBOARD',
  MANUAL: 'MANUAL',
});

export const INTAKE_CHANNELS = SOURCE_CHANNELS;

export const SOURCE_FORMATS = Object.freeze({
  QUILITY_JSON: 'QUILITY_JSON',
  ETHOS_XML: 'ETHOS_XML',
  DTCC_FLAT_FILE: 'DTCC_FLAT_FILE',
  SURELC_TIF: 'SURELC_TIF',
  MANUAL_FORM: 'MANUAL_FORM',
  CHANGE_REQUEST: 'CHANGE_REQUEST',
});

export const INTAKE_FORMATS = SOURCE_FORMATS;

export const LIFECYCLE_STATUSES = Object.freeze({
  NEW: 'New',
  APPLICATION_STARTED: 'Application Started',
  APPLICATION_SUBMITTED: 'Application Submitted',
  APPLICATION_UNDER_REVIEW: 'Application Under Review',
  BACKGROUND_CHECK: 'Background Check',
  APPOINTMENT: 'Appointment',
  CONTRACTED: 'Contracted',
  TERMINATED: 'Terminated',
});

export const WORKFLOW_STAGES = Object.freeze({
  NEW: 'NEW',
  APPLICATION_STARTED: 'APPLICATION_STARTED',
  APPLICATION_SUBMITTED: 'APPLICATION_SUBMITTED',
  APPLICATION_UNDER_REVIEW: 'APPLICATION_UNDER_REVIEW',
  LICENSING_REVIEW: 'LICENSING_REVIEW',
  BACKGROUND_CHECK: 'BACKGROUND_CHECK',
  APPOINTMENT: 'APPOINTMENT',
  APPOINTMENT_PENDING: 'APPOINTMENT_PENDING',
  DUPLICATE_REVIEW: 'DUPLICATE_REVIEW',
  MANUAL_EXCEPTION: 'MANUAL_EXCEPTION',
  CONTRACTED: 'CONTRACTED',
  TERMINATED: 'TERMINATED',
});

export const ONBOARDING_STATUSES = Object.freeze({
  DRAFT: 'draft',
  SUBMITTED: 'submitted',
  IN_REVIEW: 'in_review',
  ACTION_REQUIRED: 'action_required',
  APPROVED: 'approved',
  DECLINED: 'declined',
  WITHDRAWN: 'withdrawn',
  COMPLETED: 'completed',
});

export const WORK_ITEM_TYPES = Object.freeze({
  APPOINTMENT: 'appointment',
  BACKGROUND_CHECK: 'background_check',
  EXCEPTION: 'exception',
  DISTRIBUTION_APPROVAL: 'distribution_approval',
  AGENCY_REVIEW: 'agency_review',
  SYNC_FAILURE: 'sync_failure',
  DTCC_MANUAL_CHANGE: 'dtcc_manual_change',
  EXPLANATION_LETTER: 'explanation_letter',
});

export const WORK_ITEM_STATES = Object.freeze({
  PENDING: 'pending',
  ACTION_NEEDED: 'action_needed',
  COMPLETED: 'completed',
});

export const PRIORITIES = Object.freeze({
  LOW: 'low',
  NORMAL: 'normal',
  MEDIUM: 'medium',
  HIGH: 'high',
});

export const AUDIT_SOURCES = Object.freeze({
  PARTNER_DASHBOARD: 'partner_dashboard',
  GUIDED_JOURNEY: 'guided_journey',
  SFTP_INTAKE: 'sftp_intake',
  EMAIL_INTAKE: 'email_intake',
  DTCC_INTAKE: 'dtcc_intake',
  ETHOS_INTEGRATION: 'ethos_integration',
  QUILITY_INTEGRATION: 'quility_integration',
  SUBMISSION_SERVICE: 'submission_service',
  WORKFLOW_ENGINE: 'workflow_engine',
  OPERATIONS_WORKBENCH: 'operations_workbench',
  BACKGROUND_PROVIDER: 'background_provider',
  APPOINTMENT_PROVIDER: 'appointment_provider',
  ACTIVATION_SYNC: 'activation_sync',
  HISTORICAL_IMPORT: 'historical_import',
  CONTRACT_CHANGE: 'contract_change',
  DUPLICATE_DETECTION: 'duplicate_detection',
  ELIGIBILITY_RULES: 'eligibility_rules',
});

export const AUDIT_ACTOR_TYPES = Object.freeze({
  SYSTEM: 'system',
  PARTNER_USER: 'partner_user',
  INTERNAL_USER: 'internal_user',
});

export const INTEGRATION_SYSTEMS = Object.freeze({
  AGENT_DB: 'agent_db',
  LIFE_PRO: 'lifepro',
  HORIZON: 'horizon',
  ALI: 'ali',
});

export const PROVIDER_CODES = Object.freeze({
  NIPR: 'NIPR',
  GIACT: 'GIACT',
  AML: 'AML_DEMO',
  BACKGROUND: 'BIG',
  APPOINTMENT: 'SIRCON_VERTAFORE',
  DTCC: 'DTCC',
  ETHOS: 'ETHOS',
  HORIZON: 'HORIZON',
  DOCUSIGN: 'DOCUSIGN',
});

export const RULE_IDENTIFIERS = Object.freeze({
  ABNCA_NO_ADVANCE: 'ABNCA_NO_ADVANCE',
  AGENT_CODE_COLLISION: 'AGENT_CODE_COLLISION',
  AML_CONFIRMED_SANCTIONS_MATCH: 'AML_CONFIRMED_SANCTIONS_MATCH',
  AML_IDENTITY_DATA_REQUIRED: 'AML_IDENTITY_DATA_REQUIRED',
  AML_POSSIBLE_MATCH: 'AML_POSSIBLE_MATCH',
  APPLICANT_IDENTITY_REQUIRED: 'APPLICANT_IDENTITY_REQUIRED',
  APPOINTMENT_PENDING: 'APPOINTMENT_PENDING',
  APPOINTMENT_REUSE_AVAILABLE: 'APPOINTMENT_REUSE_AVAILABLE',
  APPOINTMENT_STATE_ELIGIBILITY_FAILED:
    'APPOINTMENT_STATE_ELIGIBILITY_FAILED',
  BACKGROUND_ADJUDICATION_REQUIRED: 'BACKGROUND_ADJUDICATION_REQUIRED',
  BACKGROUND_CHECK_PENDING: 'BACKGROUND_CHECK_PENDING',
  BACKGROUND_REUSE_AVAILABLE: 'BACKGROUND_REUSE_AVAILABLE',
  BACKGROUND_REUSE_WINDOW_EXPIRED: 'BACKGROUND_REUSE_WINDOW_EXPIRED',
  BANK_ACCOUNT_CLOSED: 'BANK_ACCOUNT_CLOSED',
  BANK_ACCOUNT_OWNERSHIP_MISMATCH: 'BANK_ACCOUNT_OWNERSHIP_MISMATCH',
  BANK_ROUTING_NUMBER_INVALID: 'BANK_ROUTING_NUMBER_INVALID',
  BANKING_DETAILS_REQUIRED: 'BANKING_DETAILS_REQUIRED',
  COMPANY_REQUIRED: 'COMPANY_REQUIRED',
  COMPLEX_HIERARCHY_CHANGE_REQUIRES_REVIEW:
    'COMPLEX_HIERARCHY_CHANGE_REQUIRES_REVIEW',
  CONTRACT_TYPE_REQUIRED: 'CONTRACT_TYPE_REQUIRED',
  CORPORATE_LICENSED_PRINCIPAL_REQUIRED:
    'CORPORATE_LICENSED_PRINCIPAL_REQUIRED',
  DTCC_CRD_NOT_FOUND: 'DTCC_CRD_NOT_FOUND',
  DTCC_IDENTITY_MISMATCH: 'DTCC_IDENTITY_MISMATCH',
  DTCC_REGISTRATION_INACTIVE: 'DTCC_REGISTRATION_INACTIVE',
  DUPLICATE_APPLICATION_IN_PROGRESS: 'DUPLICATE_APPLICATION_IN_PROGRESS',
  DUPLICATE_PARTNER_SUBMISSION: 'DUPLICATE_PARTNER_SUBMISSION',
  EO_REQUIRED: 'EO_REQUIRED',
  ESIGN_CONSENT_REQUIRED: 'ESIGN_CONSENT_REQUIRED',
  ESIGN_ENVELOPE_DECLINED: 'ESIGN_ENVELOPE_DECLINED',
  ESIGN_ENVELOPE_EXPIRED: 'ESIGN_ENVELOPE_EXPIRED',
  FOR_CAUSE_TERMINATION_BLOCK: 'FOR_CAUSE_TERMINATION_BLOCK',
  GA_CODE_REQUIRED: 'GA_CODE_REQUIRED',
  HIERARCHY_NOT_RESOLVED: 'HIERARCHY_NOT_RESOLVED',
  IMPORT_PARSE_ERROR: 'IMPORT_PARSE_ERROR',
  LICENSE_EXPIRED: 'LICENSE_EXPIRED',
  MANUAL_AGENT_CODE_REQUIRED: 'MANUAL_AGENT_CODE_REQUIRED',
  NIPR_IDENTITY_MISMATCH: 'NIPR_IDENTITY_MISMATCH',
  NIPR_PRODUCER_NOT_FOUND: 'NIPR_PRODUCER_NOT_FOUND',
  NPN_INVALID_FORMAT: 'NPN_INVALID_FORMAT',
  NPN_REQUIRED: 'NPN_REQUIRED',
  OCR_LOW_CONFIDENCE: 'OCR_LOW_CONFIDENCE',
  REQUIRED_LINE_OF_AUTHORITY_MISSING:
    'REQUIRED_LINE_OF_AUTHORITY_MISSING',
  SUITABILITY_TERMINATION_BLOCK: 'SUITABILITY_TERMINATION_BLOCK',
  SYNC_RETRY_REQUIRED: 'SYNC_RETRY_REQUIRED',
  TERMINATION_HISTORY_REVIEW_REQUIRED:
    'TERMINATION_HISTORY_REVIEW_REQUIRED',
  WILLIAM_PENN_LEVEL_30_UNSUPPORTED:
    'WILLIAM_PENN_LEVEL_30_UNSUPPORTED',
  WILLIAM_PENN_NON_TRADITIONAL_UNSUPPORTED:
    'WILLIAM_PENN_NON_TRADITIONAL_UNSUPPORTED',
});

export const VALIDATION_CODES = RULE_IDENTIFIERS;
export const RULE_IDS = RULE_IDENTIFIERS;