export const ROLES = Object.freeze({
  PARTNER: 'partner',
  AGENCY: 'agency',
  LICENSING: 'licensing',
  MANAGER: 'manager',
  DISTRIBUTION: 'distribution',
  OPERATIONS: 'operations',
  ADMIN: 'admin',
});

export const ROLE_NAMES = ROLES;

export const ROLE_LABELS = Object.freeze({
  [ROLES.PARTNER]: 'Partner',
  [ROLES.AGENCY]: 'Agency',
  [ROLES.LICENSING]: 'Licensing',
  [ROLES.MANAGER]: 'Manager',
  [ROLES.DISTRIBUTION]: 'Distribution',
  [ROLES.OPERATIONS]: 'Operations',
  [ROLES.ADMIN]: 'Administrator',
});

export const PARTNER_SCOPE_TYPES = Object.freeze({
  OWN_ORGANIZATION: 'own_organization',
  ASSIGNED_ORGANIZATIONS: 'assigned_organizations',
  ASSIGNED_WORK: 'assigned_work',
  ALL_PARTNERS: 'all_partners',
  GLOBAL: 'global',
});

export const PERMISSIONS = Object.freeze({
  VIEW_DASHBOARD: 'dashboard:view',
  VIEW_ONBOARDING: 'onboarding:view',
  CREATE_ONBOARDING: 'onboarding:create',
  UPDATE_ONBOARDING: 'onboarding:update',
  SUBMIT_ONBOARDING: 'onboarding:submit',
  REVIEW_ONBOARDING: 'onboarding:review',
  APPROVE_ONBOARDING: 'onboarding:approve',
  ASSIGN_ONBOARDING: 'onboarding:assign',
  VIEW_WORKBENCH: 'workbench:view',
  MANAGE_WORK_ITEMS: 'work_items:manage',
  REVIEW_LICENSING: 'licensing:review',
  MANAGE_APPOINTMENTS: 'appointments:manage',
  REVIEW_DISTRIBUTION: 'distribution:review',
  MANAGE_HIERARCHIES: 'hierarchies:manage',
  RESOLVE_EXCEPTIONS: 'exceptions:resolve',
  VIEW_OPERATIONS: 'operations:view',
  MANAGE_CONTRACT_CHANGES: 'contract_changes:manage',
  VIEW_REPORTS: 'reports:view',
  VIEW_NOTIFICATIONS: 'notifications:view',
  MANAGE_REFERENCE_DATA: 'reference_data:manage',
  MANAGE_USERS: 'users:manage',
  MANAGE_CONFIGURATION: 'configuration:manage',
  VIEW_DIAGNOSTICS: 'diagnostics:view',
});

const partnerPermissions = Object.freeze([
  PERMISSIONS.VIEW_DASHBOARD,
  PERMISSIONS.VIEW_ONBOARDING,
  PERMISSIONS.CREATE_ONBOARDING,
  PERMISSIONS.UPDATE_ONBOARDING,
  PERMISSIONS.SUBMIT_ONBOARDING,
  PERMISSIONS.VIEW_NOTIFICATIONS,
]);

const agencyPermissions = Object.freeze([
  ...partnerPermissions,
  PERMISSIONS.REVIEW_ONBOARDING,
  PERMISSIONS.VIEW_REPORTS,
]);

const licensingPermissions = Object.freeze([
  PERMISSIONS.VIEW_DASHBOARD,
  PERMISSIONS.VIEW_ONBOARDING,
  PERMISSIONS.UPDATE_ONBOARDING,
  PERMISSIONS.REVIEW_ONBOARDING,
  PERMISSIONS.VIEW_WORKBENCH,
  PERMISSIONS.MANAGE_WORK_ITEMS,
  PERMISSIONS.REVIEW_LICENSING,
  PERMISSIONS.MANAGE_APPOINTMENTS,
  PERMISSIONS.RESOLVE_EXCEPTIONS,
  PERMISSIONS.VIEW_NOTIFICATIONS,
]);

const managerPermissions = Object.freeze([
  PERMISSIONS.VIEW_DASHBOARD,
  PERMISSIONS.VIEW_ONBOARDING,
  PERMISSIONS.UPDATE_ONBOARDING,
  PERMISSIONS.REVIEW_ONBOARDING,
  PERMISSIONS.APPROVE_ONBOARDING,
  PERMISSIONS.ASSIGN_ONBOARDING,
  PERMISSIONS.VIEW_WORKBENCH,
  PERMISSIONS.MANAGE_WORK_ITEMS,
  PERMISSIONS.REVIEW_LICENSING,
  PERMISSIONS.MANAGE_APPOINTMENTS,
  PERMISSIONS.REVIEW_DISTRIBUTION,
  PERMISSIONS.RESOLVE_EXCEPTIONS,
  PERMISSIONS.VIEW_OPERATIONS,
  PERMISSIONS.MANAGE_CONTRACT_CHANGES,
  PERMISSIONS.VIEW_REPORTS,
  PERMISSIONS.VIEW_NOTIFICATIONS,
]);

const distributionPermissions = Object.freeze([
  PERMISSIONS.VIEW_DASHBOARD,
  PERMISSIONS.VIEW_ONBOARDING,
  PERMISSIONS.UPDATE_ONBOARDING,
  PERMISSIONS.REVIEW_ONBOARDING,
  PERMISSIONS.VIEW_WORKBENCH,
  PERMISSIONS.MANAGE_WORK_ITEMS,
  PERMISSIONS.REVIEW_DISTRIBUTION,
  PERMISSIONS.MANAGE_HIERARCHIES,
  PERMISSIONS.RESOLVE_EXCEPTIONS,
  PERMISSIONS.MANAGE_CONTRACT_CHANGES,
  PERMISSIONS.VIEW_REPORTS,
  PERMISSIONS.VIEW_NOTIFICATIONS,
]);

const operationsPermissions = Object.freeze([
  PERMISSIONS.VIEW_DASHBOARD,
  PERMISSIONS.VIEW_ONBOARDING,
  PERMISSIONS.CREATE_ONBOARDING,
  PERMISSIONS.UPDATE_ONBOARDING,
  PERMISSIONS.SUBMIT_ONBOARDING,
  PERMISSIONS.REVIEW_ONBOARDING,
  PERMISSIONS.ASSIGN_ONBOARDING,
  PERMISSIONS.VIEW_WORKBENCH,
  PERMISSIONS.MANAGE_WORK_ITEMS,
  PERMISSIONS.RESOLVE_EXCEPTIONS,
  PERMISSIONS.VIEW_OPERATIONS,
  PERMISSIONS.MANAGE_CONTRACT_CHANGES,
  PERMISSIONS.VIEW_REPORTS,
  PERMISSIONS.VIEW_NOTIFICATIONS,
]);

const adminPermissions = Object.freeze(Object.values(PERMISSIONS));

export const ROLE_PERMISSION_MATRIX = Object.freeze({
  [ROLES.PARTNER]: partnerPermissions,
  [ROLES.AGENCY]: agencyPermissions,
  [ROLES.LICENSING]: licensingPermissions,
  [ROLES.MANAGER]: managerPermissions,
  [ROLES.DISTRIBUTION]: distributionPermissions,
  [ROLES.OPERATIONS]: operationsPermissions,
  [ROLES.ADMIN]: adminPermissions,
});

export const PERMISSION_MATRIX = ROLE_PERMISSION_MATRIX;

export const ROLE_PARTNER_SCOPE_MATRIX = Object.freeze({
  [ROLES.PARTNER]: PARTNER_SCOPE_TYPES.OWN_ORGANIZATION,
  [ROLES.AGENCY]: PARTNER_SCOPE_TYPES.OWN_ORGANIZATION,
  [ROLES.LICENSING]: PARTNER_SCOPE_TYPES.ASSIGNED_WORK,
  [ROLES.MANAGER]: PARTNER_SCOPE_TYPES.ASSIGNED_ORGANIZATIONS,
  [ROLES.DISTRIBUTION]: PARTNER_SCOPE_TYPES.ALL_PARTNERS,
  [ROLES.OPERATIONS]: PARTNER_SCOPE_TYPES.ALL_PARTNERS,
  [ROLES.ADMIN]: PARTNER_SCOPE_TYPES.GLOBAL,
});

export const ROLE_SCOPE_MATRIX = ROLE_PARTNER_SCOPE_MATRIX;

export const INTERNAL_ROLES = Object.freeze([
  ROLES.LICENSING,
  ROLES.MANAGER,
  ROLES.DISTRIBUTION,
  ROLES.OPERATIONS,
  ROLES.ADMIN,
]);

export const EXTERNAL_ROLES = Object.freeze([ROLES.PARTNER, ROLES.AGENCY]);

export const ALL_ROLES = Object.freeze(Object.values(ROLES));